analytics:
  - packages/analytics/*
  - packages/analytics/**/*

utils:
  - packages/auth/*
  - packages/auth/**/*

admin:
  - packages/core/*
  - packages/core/**/*

users:
  - packages/type/*
  - packages/type/**/*

starter:
  - apps/next-product-starter/*
  - packages/next-product-starter/**/*

cypress:
  - cypress/*
  - cypress/**/*

repo:
  - ./*
